apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pv9y4nu6e-go
  janus-idp.io/tekton: pv9y4nu6e-go
  backstage.io/kubernetes-id: pv9y4nu6e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pv9y4nu6e-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
